server:
  port: ${SERVER_PORT:9999}
spring:
  datasource:
    password: ${MYSQL_PASSWORD:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:user_registration01}
    username: ${MYSQL_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true